In [2]:
import networkx as nx
import numpy as np
from torch_geometric.utils import remove_self_loops, coalesce
import torch
edge = np.array([[0,1,0],
                 [1,1,0],
                 [0,1,1.5]])
node_features = np.array([[1, 2],
                          [3, 4],
                          [5, 6]])

# Create graph from adjacency matrix
G = nx.from_numpy_array(edge)

G.edges(data=True)

A = nx.to_scipy_sparse_array(G, format='coo')

adj = A.tocoo()
print(adj.col)
print(adj.row)
edge_att = np.zeros(len(adj.row))
for i in range(len(adj.row)):
    edge_att[i] = edge[adj.row[i], adj.col[i]]
num_nodes = 3
edge_index = np.vstack([adj.row, adj.col])
edge_index, edge_att = remove_self_loops(torch.from_numpy(edge_index), torch.from_numpy(edge_att))
print(edge_index,edge_att)
print(coalesce(edge_index=edge_index,edge_attr=edge_att,num_nodes=num_nodes))


[1 1 2 2 0 1 1 2 1 2]
[0 1 1 2 1 1 2 2 1 2]
tensor([[0, 1, 1, 2],
        [1, 2, 0, 1]]) tensor([1., 0., 1., 1.], dtype=torch.float64)
(tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]]), tensor([1., 1., 0., 1.], dtype=torch.float64))


In [77]:
import torch
from torch_geometric.utils import coalesce

# Example edge index with duplicate edges
edge_index = torch.tensor([[0, 1, 1, 2, 2, 2],
                           [1, 0, 0, 1, 1, 2]], dtype=torch.long)

# Example edge attributes for each edge
edge_att = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float)

# Number of nodes
num_nodes = 3

# Coalesce to merge duplicate edges and sort
edge_index, edge_att = coalesce(edge_index, edge_att)

print("Coalesced edge index:\n", edge_index)
print("Coalesced edge attributes:\n", edge_att)


Coalesced edge index:
 tensor([[0, 1, 2, 2],
        [1, 0, 1, 2]])
Coalesced edge attributes:
 tensor([1., 5., 9., 6.])


In [88]:
import os
import glob
import pandas as pd

# Get all files with 'Longi' in the filename
long_files = glob.glob('/media/hang/EXTERNAL_US/Data/1_HANG_FDG_PET/ADNI_Second_organized/KDE_Results/raw/*Longi*')

# Iterate over the list of files
for long_file in long_files:
    # Print the file if it does not end with 'Z_scoringLongitude.mat'
    os.remove(long_file)
